baseURL               = "https://dh.little-data.top/"
languageCode          = "zh-CN"
title                 = "lite-navigate 网址导航"
theme                 = "WebStack-Hugo"
preserveTaxonomyNames = true
disablePathToLower    = true
hasCJKLanguage        = true
publishDir            = "doc"


[params]
    author        = "Little-data"
    description   = "lite-navigate 网址导航 | Hugo 主题 BY Bio IT 爱好者"
    siteurl       = "./"
    upload        = "https://forms.office.com/e/srKdi2jq3T"  # 左侧导航栏的"网站提交"
    about         = "./about"   # 左侧导航栏的"关于导航"页面(./about)
    repository    = "https://github.com/shenweiyan/WebStack-Hugo"
    enablePreLoad = true		    		           # 网站完全打开前预加载动画
    textPreLoad   = "lite-navigate 网址导航" 		           # 预加载的动画文字, 只有当enablePreLoad=true时生效
    expandSidebar = false                                          # 默认展开左侧边导航栏
    logosPath     = "assets/images/logos"			   # 网站每个导航地址logo存放地址
    defaultLogo   = "assets/images/logos/default.webp"             # logo图片资源不存在或者错误时, 默认显示的logo; 该参数如为空,将会一直加载对应的logo,直至成功
    baiduhmid     = 'c96d493d601c95b96a35949c4feea0a2'             # 百度统计 hm.src 的 ID

[params.qweather]
    key = "085791e805a24491b43b06cf58ab31e7"

[params.images]
    favicon           = "assets/images/favicon.png"
    searchImageL      = "assets/images/bg-math.jpg"		#搜索部分浅色背景图
    searchImageD      = "assets/images/bg-math-b.jpg"		#搜索部分深色背景图
    logoExpandLight   = "assets/images/logos/default.webp"
    logoExpandDark    = "assets/images/logos/default.webp"
    logoCollapseLight = "assets/images/logos/default.webp"
    logoCollapseDark  = "assets/images/logos/default.webp"

[markup.goldmark.renderer]
    unsafe = true

[params.footer]
    copyright = '本站内容源自互联网，如有内容侵犯了你的权益，请联系删除相关内容，请到个人博客查看联系方式 <br/>&copy; 2021 - {year} By [WebStack-Hugo](https://github.com/shenweiyan/WebStack-Hugo) | [主站博客](https://blog.little-data.top/) | <br/>'
